Hotfix user not returning list
stfc/st2-cloud-pack pull request #139
Opened 2023-10-02 14:45 UTC by DavidFair

### Description:
Fixes UserRunner not returning a list, this was seen by @meoflynn 

### Special Notes:

---

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [ ] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2023-10-02 15:27 UTC, anish-mudaraddi commented
rewrite your tests once #141 is merged

2023-10-02 15:28 UTC, anish-mudaraddi requested changes
rewrite your tests once #141 is merged

2023-10-02 16:13 UTC, meoflynn requested changes

2023-10-03 09:08 UTC, DavidFair commented on lib/openstack_query/runners/user_runner.py
> +            val = conn.identity.find_user("id", ignore_missing=True)
Ah I flagged this last night too as a potential bug, I wanted to double check this morning but that confirms it. Thanks :+1:

2023-10-03 10:40 UTC, meoflynn approved these changes

2023-10-03 10:52 UTC, anish-mudaraddi approved these changes
LGTM

2023-10-03 10:53 UTC, merged