Adding to_csv functions to the query library
stfc/st2-cloud-pack pull request #194
Opened 2023-12-01 15:35 UTC by AspectVI

### Description:

### Submitter:

Have you (where applicable):

* [ ] Added unit tests?
* [ ] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2023-12-04 12:09 UTC, anish-mudaraddi approved these changes

2023-12-04 12:29 UTC, khalford requested changes

2023-12-04 13:25 UTC, AspectVI commented on tests/lib/openstack_query/query_blocks/test_query_output.py
> +                "user_name": "user1",
changed

2023-12-04 13:25 UTC, AspectVI commented on tests/lib/openstack_query/query_blocks/test_query_output.py
> +                "user_name": "user2",
changed

2023-12-04 13:26 UTC, AspectVI commented on tests/lib/openstack_query/query_blocks/test_query_output.py
> +                "user_name": "user2",
altered

2023-12-04 14:02 UTC, AspectVI commented on lib/openstack_query/query_blocks/query_output.py
> +        for p_id, p_info in data.items():
After a further look it seem to be the meta data of the dict/lists that are past in. Then this is used to loop the correct amount of times and then later assign the names as the file name for the created files.

2023-12-04 15:12 UTC, anish-mudaraddi commented on lib/openstack_query/query_blocks/query_output.py
> +        for p_id, p_info in data.items():
yea we're looping through group name and the group items - which is a list of query results that belong the that group. 
so maybe `group_name`, `group_items`

2023-12-04 15:57 UTC, AspectVI commented on lib/openstack_query/query_blocks/query_output.py
> +        for p_id, p_info in data.items():
Cool, ill do that

2023-12-05 08:24 UTC, khalford approved these changes

2023-12-05 08:24 UTC, khalford commented
LGTM

2023-12-05 08:40 UTC, AspectVI commented
@khalford @anish-mudaraddi Am I fin to merge this PR, the codecov is falling over itself and causing test fails.

2023-12-05 08:48 UTC, merged