ENH: use email wrapper and styling
stfc/st2-cloud-pack pull request #208
Opened 2024-01-09 16:00 UTC by anish-mudaraddi

Add styling to make html emails look better. 
Styles can be defined in wrapper.html with style tags

We use css-inline to automatically convert style tags to html inline styles which is required when styling html emails

2024-01-09 16:14 UTC, Koldstream submitted a review, later dismissed

2024-01-10 11:23 UTC, khalford requested changes

2024-01-10 11:23 UTC, khalford commented on lib/email_api/emailer.py
> +import css_inline
As far as I can see, you only use one method from `css_inline`:
```suggestion
from css_inline import CSSInliner
```

2024-01-10 11:23 UTC, khalford commented on lib/email_api/emailer.py
> +            inliner = css_inline.CSSInliner(keep_style_tags=True)
If you change the import:
```suggestion
            inliner = CSSInliner(keep_style_tags=True)
```

2024-01-10 11:47 UTC, khalford approved these changes

2024-01-10 13:29 UTC, khalford approved these changes

2024-01-10 14:03 UTC, Koldstream approved these changes

2024-01-10 14:07 UTC, merged