ENH: add send decom image action
stfc/st2-cloud-pack pull request #210
Opened 2024-01-10 14:38 UTC by anish-mudaraddi

Adds the send decom image script and action

2024-01-10 15:05 UTC, khalford submitted a review, later dismissed
LGTM

2024-01-15 14:43 UTC, DavidFair requested changes

2024-01-15 14:43 UTC, DavidFair commented on lib/workflows/send_decom_image_email.py
> +    )
These should be `if` statements, asserts are for programming errors which shouldn't happen

Instead this should be either a `ValueError` or something similar

2024-01-15 14:43 UTC, DavidFair commented on lib/workflows/send_decom_image_email.py
> +        ), "End Of Life string must be in format YYYY/MM/DD"
^

2024-01-15 14:43 UTC, DavidFair commented on lib/workflows/send_decom_image_email.py
> +                else server_query.to_html(groups=[user_id], include_group_titles=False),
Nit: can we do these if-else outside of this method call as it's a bit difficult to read

2024-01-15 16:24 UTC, DavidFair approved these changes

2024-01-15 16:24 UTC, khalford approved these changes

2024-01-15 16:49 UTC, merged