MAINT: rewrite results container tests
stfc/st2-cloud-pack pull request #220
Opened 2024-04-18 09:18 UTC by anish-mudaraddi

rewrite ResultsContainer class and tests so we don't need to access protected methods for tests

2024-04-18 13:48 UTC, khalford requested changes
LGTM only doc fixes

2024-04-18 13:48 UTC, khalford commented on lib/openstack_query/query_blocks/results_container.py
>          static helper method to return forwarded values that match a given property value. Used for chaining
```suggestion
        helper method to return forwarded values that match a given property value. Used for chaining
```

2024-04-18 13:48 UTC, khalford commented on tests/lib/openstack_query/query_blocks/test_result_container.py
> +    Helper function to mock a Result object with a mocked value to return when get_prop() is caled
```suggestion
    Helper function to mock a Result object with a mocked value to return when get_prop() is called
```

2024-05-02 10:53 UTC, AspectVI approved these changes

2024-05-03 07:15 UTC, khalford approved these changes

2024-05-13 08:29 UTC, merged