TST: refactor client-side-handler tests
stfc/st2-cloud-pack pull request #226
Opened 2024-05-02 10:56 UTC by anish-mudaraddi

refactor client-side-handler tests to remove need for accessing protected methods

2024-06-06 08:08 UTC, khalford requested changes

2024-06-06 08:08 UTC, khalford commented on lib/openstack_query/handlers/client_side_handler_generic.py
> +        return not any(prop == val for val in values)
```suggestion
        some_var = any(prop == val for val in values)
        return not some_var
```

2024-06-06 08:08 UTC, khalford commented on lib/openstack_query/handlers/client_side_handler_string.py
>          return bool(re.match(re.compile(rf"{value}"), prop))
```suggestion
        some_var = re.match(re.compile(rf"{value}"), prop)
        return bool(some_var)
```

2024-06-07 14:56 UTC, anish-mudaraddi commented on lib/openstack_query/handlers/client_side_handler_datetime.py
> +        return not prop_timestamp > given_timestamp
in this case it would be 
``` 
return prop_timestamp <= given_timestamp
```
would you like me to change this?

2024-06-07 15:30 UTC, RWhiting78 approved these changes

2024-06-10 08:36 UTC, khalford approved these changes

2024-06-10 08:36 UTC, merged