MAINT: refactor Openstack API - network
stfc/st2-cloud-pack pull request #245
Opened 2024-08-05 10:12 UTC by anish-mudaraddi

part of remove-orquesta feature branch 
refactor class into standalone functions - split into 3 modules - router, network and subnet

2024-08-21 14:23 UTC, meoflynn requested changes

2024-08-21 14:23 UTC, meoflynn commented on tests/lib/openstack_api/test_openstack_network.py
> +        mock_project_identifier = "foo"
Could we add docstrings to these methods?

2024-09-04 09:34 UTC, meoflynn approved these changes

2024-09-04 09:35 UTC, meoflynn commented
LGTM - there are some unit tests failing that need to be checked

2024-09-04 12:44 UTC, khalford approved these changes

2024-09-04 12:45 UTC, merged