ENH: Add Search Icinga Actions
stfc/st2-cloud-pack pull request #270
Opened 2024-10-07 10:54 UTC by gmatthews20

### Description:
Add actions to search by hosts/services state or name
Add search tests

---

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [x] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2024-10-10 08:16 UTC, meoflynn requested changes

2024-10-10 08:16 UTC, meoflynn commented on lib/workflows/icinga_search.py
> +    def get_value(a: Dict, filter1: str, states=None) -> str:
Could we add a docstring to this method?

2024-10-10 08:16 UTC, meoflynn commented on tests/lib/icinga_api/test_query_objects.py
> +def test_query_object_without_joins_success(mock_post, joins):
Could you add a docstring to this test?

2024-10-14 12:31 UTC, anish-mudaraddi approved these changes

2024-10-14 12:31 UTC, merged