ENH: Add webhook output to search actions
stfc/st2-cloud-pack pull request #273
Opened 2024-10-10 12:48 UTC by gmatthews20

### Description:

Add to_webhook output which sends the results of a search action to a webhook. 
This will allow the output of a search action to send triggers for each item in the results to a webhook which will create a trigger to start other actions.

### Special Notes:

---

### Submitter:

Have you (where applicable):

* [ ] Added unit tests?
* [ ] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2024-10-10 14:14 UTC, meoflynn requested changes

2024-10-10 14:14 UTC, meoflynn commented on lib/workflows/to_webhook.py
> +def to_webhook(webhook: str, payload: List[Dict]) -> None:
Could you add a docstring to this method?

2024-10-10 14:14 UTC, meoflynn commented on tests/lib/workflows/test_to_webhook.py
> +def test_to_webhook_success(mock_post):
Could you add a docstring to this method?

2024-10-10 14:14 UTC, meoflynn commented on tests/lib/workflows/test_to_webhook.py
> +def test_to_webhook_failure(mock_post):
Could you add a docstring to this method?

2024-10-11 08:30 UTC, meoflynn approved these changes

2024-10-14 12:27 UTC, anish-mudaraddi approved these changes

2024-10-14 12:28 UTC, anish-mudaraddi commented
eventually every action should have a webook - but this is fine for now

2024-10-14 12:28 UTC, merged