ENH: Add Hypervisor state sensor
stfc/st2-cloud-pack pull request #274
Opened 2024-10-10 16:09 UTC by gmatthews20

### Description:

Sensor monitors hypervisors for state changes and dispatches a trigger when a change is detected

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [x] Checked the latest commit runs on Dev?
* [x] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2024-10-14 14:42 UTC, meoflynn requested changes

2024-10-14 14:42 UTC, meoflynn commented on lib/enums/hypervisor_states.py
> +class HypervisorState(Enum):
Could you add a docstring describing this class?

2024-10-14 14:42 UTC, meoflynn commented on sensors/src/hypervisor_state_sensor.py
> +        # closing the connections to external system here.
Could you add these as a docstring instead of a comment?

2024-10-14 14:42 UTC, meoflynn commented on sensors/src/hypervisor_state_sensor.py
> +        # This method is called when trigger is deleted
Could you add these comments as docstrings instead?

2024-10-14 14:42 UTC, meoflynn commented on tests/sensors/test_hypervisor_state_sensor.py
> +class TestHypervisorStateSensor(unittest.TestCase):
could you add a docstring to the class?

2024-10-14 14:42 UTC, meoflynn commented on tests/sensors/test_hypervisor_state_sensor.py
> +    def test_poll(self, mock_query_hypervisor_state, mock_get_hypervisor_state):
could you add a docstring to this test?

2024-10-17 12:56 UTC, meoflynn approved these changes

2024-10-17 13:58 UTC, RJaliliSTFC approved these changes

2024-10-18 08:25 UTC, merged