Hypervisor Patch and Reboot workflow
stfc/st2-cloud-pack pull request #282
Opened 2024-11-13 15:47 UTC by lizsalmon

### Description:

The hypervisors start a downtime and during the downtime two ssh commands are run on the hv, patch and reboot.  These will work with the stackstorm user (currently in an aquilon sandbox) to run a patch and a reboot script.  

---

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [x] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2024-11-13 16:26 UTC, gmatthews20 requested changes
Looks good just a few small tweaks

2024-11-13 16:26 UTC, gmatthews20 commented on actions/hv.patch.reboot.yaml
> +    required: true
We could remove this parameter as the hypervisor hostname is used as the name in icinga

2024-11-13 16:26 UTC, gmatthews20 commented on actions/hv.patch.reboot.yaml
> +  host:
I think `hypervisor_name` may be better here, we can use this for both icinga and ssh connection, and also matches other workflows

2024-11-13 16:26 UTC, gmatthews20 commented on lib/workflows/hv_patch_and_reboot.py
> +    host: str,
See previous comment on parameters

2024-11-13 16:26 UTC, gmatthews20 commented on lib/workflows/hv_patch_and_reboot.py
> +    start_time = datetime.datetime.now()
We should use `datetime.utcnow()` as icinga expects the time to be in UTC and makes sure its not affected by DST

2024-11-13 16:26 UTC, gmatthews20 commented on lib/workflows/hv_patch_and_reboot.py
> +        reboot_out = ssh_client.run_command_on_host("reboot").decode()
I think it might make sense to move the `decode` to the return statement

2024-11-13 16:26 UTC, gmatthews20 commented on lib/workflows/hv_patch_and_reboot.py
> +def patch_and_reboot(
Can you add a docstring to this function

2024-11-13 16:26 UTC, gmatthews20 commented on tests/lib/workflows/test_hv_patch_and_reboot.py
> +    mock_ssh_conn.return_value.run_command_on_host.assert_any_call("reboot")
I think this should be `assert_called_once_with`

2024-11-13 16:26 UTC, gmatthews20 commented on tests/lib/workflows/test_hv_patch_and_reboot.py
> +def test_failed_schedule(mock_remove_downtime, mock_ssh_conn, mock_schedule_downtime):
I think this should be called `test_failed_schedule_downtime`

2024-11-13 16:26 UTC, gmatthews20 commented on tests/lib/workflows/test_hv_patch_and_reboot.py
> +    mock_remove_downtime.assert_called_once()
Could these be `assert_called_once_with`

2024-11-14 09:13 UTC, gmatthews20 commented on lib/workflows/hv_patch_and_reboot.py
> +        )
Each of the icinga and ssh command will raise their own exceptions so we don't need to catch them and re-raise them

2024-11-14 10:02 UTC, khalford commented on lib/workflows/hv_patch_and_reboot.py
> +        )
👍

2024-11-14 13:37 UTC, khalford approved these changes

2024-11-14 14:21 UTC, gmatthews20 approved these changes

2024-11-14 14:21 UTC, merged