Migrate VM's not in ACTIVE state
stfc/st2-cloud-pack pull request #293
Opened 2024-12-20 13:18 UTC by lizsalmon

### Description:
- Added in cold migration if the state is STUTOFF
- Returns an error if the state is not ACTIVE or SHUTOFF
- Added the snapshot and migrate function into the `openstack_api` so that we don't need the extra `server_migrate.py` file and then adjusted the action to run from the api rather than a workflow.  

---

### Submitter:

Have you (where applicable):

* [x] Added unit tests?
* [x] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2025-01-06 15:37 UTC, anish-mudaraddi requested changes

2025-01-06 15:37 UTC, anish-mudaraddi commented on lib/openstack_api/openstack_server.py
> +        )
here's a more concise way to write this

```python
if server_status not in ["ACTIVE", "SHUTOFF"]:
    raise ValueError(...)

if server_status == "SHUTOFF":
    return conn.compute.migrate_server(...)
return conn.compute.live_migrate_server(...)
```

saves you a few lines :) - makes it easier to read too!

2025-01-06 15:40 UTC, anish-mudaraddi commented on lib/workflows/search_by_property.py
> +        query.select(*properties_to_select, "server_id", "server_status")
why do you need this?

2025-01-07 10:59 UTC, khalford requested changes

2025-01-07 10:59 UTC, khalford commented on lib/openstack_api/openstack_server.py
>          )
I wonder if it's better to check for active and shutoff before migrate? The way it currently is. We will build up snapshots of every VM even if we don't migrate them.
```suggestion
   if server_status not in ["ACTIVE", "SHUTOFF"]:
        raise ValueError(
            f"Server status: {server_status}. The server must be ACTIVE or SHUTOFF to be migrated"
        )
    if snapshot:
        snapshot_server(conn=conn, server_id=server_id)
    
```

2025-01-07 11:57 UTC, lizsalmon commented on lib/openstack_api/openstack_server.py
>          )
Yeah that seems like a more sensible option to me, thanks- I will change it now

2025-01-07 12:08 UTC, khalford approved these changes

2025-01-07 16:09 UTC, gmatthews20 commented on lib/workflows/search_by_property.py
> +        query.select(*properties_to_select, "server_id", "server_status")
the `to_webhook` functions just sends whichever properties you've selected with the query.

Something like this to send everything might work better saves writing checks for each webhook
`to_webhook(webhook=webhook, payload=query.select_all().to_props())`

2025-01-08 10:41 UTC, lizsalmon commented on lib/workflows/search_by_property.py
> +        query.select(*properties_to_select, "server_id", "server_status")
Ah sorry yeah that makes sense! Just changed.

2025-01-08 10:55 UTC, anish-mudaraddi approved these changes
Thanks @lizsalmon @gmatthews20 for sorting this out - looks much better

2025-01-08 10:56 UTC, khalford approved these changes

2025-01-08 10:57 UTC, merged