Automate Hypervisor Updates
stfc/st2-cloud-pack pull request #64
Opened 2022-10-21 12:46 UTC by Ziggiyzoo

### Description:

### Special Notes:

---

### Submitter:

Have you (where applicable):

* [ ] Added unit tests?
* [ ] Checked the latest commit runs on Dev?
* [ ] Updated the example config file(s) and README?

---

### Reviewer

Does this PR:

* [ ] Place non-StackStorm code into the `lib` directory?
* [ ] Have unit tests for the action/sensor and `lib` layers?
* [ ] Have clear and obvious action parameter names and descriptions?

2022-11-15 14:35 UTC, DavidFair commented on tests/lib/test_openstack_hypervisor.py
> +    def test_get_all_empty_hvs_without_disabled_hvs(self):
We need tests that `vcpus_user > 0` and `running_vms > 0` correctly filter out those HVs instead of returning them as eligible

2022-11-17 14:22 UTC, meoflynn requested changes

2022-11-17 14:22 UTC, meoflynn commented on config.schema.yaml
> +  description: Automated Updater Settings and tokens
This should be wrapped in " " as it's a String.

2022-11-17 14:22 UTC, meoflynn commented on config.schema.yaml
> +  description: Automated Updater Settings and tokens
Maybe update the description to "Cloud name to use in automated jobs"

2022-11-17 14:22 UTC, meoflynn commented on config.schema.yaml
> +      description: "Cloud to use when running Automated Update Poll on Dev"
Change from "Automated Update Poll" to "Automated Jobs on Dev"

2022-11-17 14:22 UTC, meoflynn commented on config.schema.yaml
> +      description: "Cloud to use when running Automated Update Poll on Prod"
^

2022-11-17 14:22 UTC, meoflynn commented on lib/openstack_api/openstack_hypervisor.py
> +    def search_all_hvs(self, cloud_account: str) -> List[Hypervisor]:
Need to add back in `**_` as the OpenStack Query object may require this

2022-11-17 14:22 UTC, meoflynn commented on lib/openstack_api/openstack_hypervisor.py
> +            ):
This check is deprecated, we should replace this with the latest equivalent

2022-11-17 14:22 UTC, meoflynn commented on sensors/src/hypervisor_polling_sensor.py
> +        #     hvs_to_update = hvs_to_update[0:int(list_length * (PERCENTAGE_TO_REBOOT / 100))]
Let's add this into a new issue

2022-12-01 13:52 UTC, meoflynn requested changes

2022-12-01 13:52 UTC, meoflynn commented on config.schema.yaml
> +      required: true
`dev_cloud` and `selected_env` have the same descriptions. Are these duplicate properties?

Maybe update the description for `selected_env` to separate it from the `dev_cloud` property?

2023-12-06 14:16 UTC, DavidFair commented
@anish-mudaraddi Are you happy to adopt this?

2023-12-06 17:57 UTC, anish-mudaraddi commented
i'm closing this - I've looked over the code and there isn't anything useful here
It's adding a Sensor for polling hypervisors but this should really be an Action that is run periodically by a Cron job. 

A Sensor is for interacting with external services - this pack is built to run Openstack commands so we shouldn't need a sensor to query hypervisors - we should just create an Action the queries for hypervisors which are empty (using the query library) that is run periodically. 

This has the added benefit of allowing us to specify the cloud domain and other parts we can fine tune easier via writing one or more triggers.

This pack doesn't implement any rebooting either - I think the idea was to dispatch a trigger called `openstack.reboot_hypervisors` but it doesn't do that at the moment and there's no action that can handle that yet. There aren't any defined Rules for this.

I'll work on this in the new year

2023-12-06 17:57 UTC, closed without merging